#!/usr/bin/env bash
# ci reindex — regenerate index.md from frontmatter.

# Group classification for a repo-relative path.
# Emits two tab-separated fields: group-name  subgroup-name.
_r_classify() {
  local rel="$1"
  case "$rel" in
    shared/*/*)
      # Two-or-more-segment path under shared/; subgroup is the first subdir
      local sub
      sub=$(printf '%s' "$rel" | awk -F/ '{print $1"/"$2"/"}')
      printf 'Shared components\t%s\n' "$sub"
      ;;
    shared/*)
      printf 'Shared components\tshared/\n'
      ;;
    functions/*/*)
      local sub
      sub=$(printf '%s' "$rel" | awk -F/ '{print $1"/"$2"/"}')
      printf 'Functions\t%s\n' "$sub"
      ;;
    functions/*)
      printf 'Functions\tfunctions/\n'
      ;;
    sources/*/*)
      local sub
      sub=$(printf '%s' "$rel" | awk -F/ '{print $1"/"$2"/"}')
      printf 'Sources\t%s\n' "$sub"
      ;;
    sources/*)
      printf 'Sources\tsources/\n'
      ;;
    *)
      printf 'Meta\t\n'
      ;;
  esac
}

# Build a TSV of all cataloged entries to stdout.
# Columns: group \t subgroup \t rel \t title \t desc \t motion \t segment \t last_reviewed
_r_collect() {
  local rel
  ci_iter_pages | while read -r rel; do
    ci_has_frontmatter "$rel" || continue
    local title desc last_reviewed motion segment classification group subgroup
    title=$(ci_get_field "$rel" title)
    desc=$(ci_get_field "$rel" description)
    last_reviewed=$(ci_get_field "$rel" last_reviewed)
    motion=$(ci_get_list "$rel" motion | paste -sd ',' - | sed 's/,/, /g')
    segment=$(ci_get_list "$rel" segment | paste -sd ',' - | sed 's/,/, /g')
    classification=$(_r_classify "$rel")
    group=$(printf '%s' "$classification" | cut -f1)
    subgroup=$(printf '%s' "$classification" | cut -f2)
    # Use ASCII unit-separator (0x1F) instead of tab. Tab is an IFS
    # whitespace char in bash, which causes `read` to collapse empty
    # adjacent fields into one.
    printf '%s\x1f%s\x1f%s\x1f%s\x1f%s\x1f%s\x1f%s\x1f%s\n' \
      "$group" "$subgroup" "$rel" "$title" "$desc" "$motion" "$segment" "$last_reviewed"
  done
}

# Render a single entry (bullet line).
_r_render_entry() {
  local rel="$1" title="$2" desc="$3" motion="$4" segment="$5" last_reviewed="$6"
  local filename
  filename=$(basename "$rel")
  local meta_parts=() meta=""
  [[ -n "$motion" ]] && meta_parts+=("motion: ${motion}")
  [[ -n "$segment" ]] && meta_parts+=("segment: ${segment}")
  [[ -n "$last_reviewed" && "$last_reviewed" != "null" ]] && meta_parts+=("reviewed ${last_reviewed}")
  if [[ ${#meta_parts[@]} -gt 0 ]]; then
    local IFS='|'
    local joined="${meta_parts[*]}"
    meta=" *(${joined//|/; })*"
  fi
  # Output the bullet. Using printf with an explicit format string; the
  # leading "-" is inside the format, not a flag, so printf doesn't
  # interpret it.
  printf '%s\n' "- [\`${filename}\`](${rel}) — ${desc}${meta}"
}

# Emit the full index.md content to stdout.
_r_generate() {
  local root
  root=$(ci_repo_root)
  cd "$root"

  local commit_sha now
  if command -v git >/dev/null 2>&1; then
    commit_sha=$(git rev-parse --short HEAD 2>/dev/null)
    [[ -z "$commit_sha" ]] && commit_sha="unknown"
  else
    commit_sha="unknown"
  fi
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  local tmp
  tmp=$(mktemp 2>/dev/null || mktemp -t ci-reindex)
  _r_collect > "$tmp"

  # Header
  printf '# Company Index — Catalog\n\n'
  printf '> Generated by `ci reindex` from page frontmatter. Do not edit by hand.\n'
  printf '> Last regenerated: %s (commit %s)\n\n' "$now" "$commit_sha"

  # Counts. Field separator is \x1f (unit separator) throughout.
  local US=$'\x1f'
  local total_shared total_functions total_sources total_meta
  total_shared=$(awk -F"$US" '$1 == "Shared components"' "$tmp" | wc -l | tr -d ' ')
  total_functions=$(awk -F"$US" '$1 == "Functions"' "$tmp" | wc -l | tr -d ' ')
  total_sources=$(awk -F"$US" '$1 == "Sources"' "$tmp" | wc -l | tr -d ' ')
  total_meta=$(awk -F"$US" '$1 == "Meta"' "$tmp" | wc -l | tr -d ' ')

  # Emit groups in fixed order
  local groups=("Shared components" "Functions" "Sources" "Meta")
  local g
  for g in "${groups[@]}"; do
    local count
    count=$(awk -F"$US" -v g="$g" '$1 == g' "$tmp" | wc -l | tr -d ' ')
    [[ "$count" == "0" ]] && continue

    printf '## %s\n\n' "$g"

    if [[ "$g" == "Meta" ]]; then
      # Flat — sort by path
      awk -F"$US" -v g="$g" '$1 == g' "$tmp" | sort -t "$US" -k3,3 | while IFS="$US" read -r _group _subgroup rel title desc motion segment last_reviewed; do
        _r_render_entry "$rel" "$title" "$desc" "$motion" "$segment" "$last_reviewed"
      done
      printf '\n'
    else
      # Grouped — emit each subgroup with ### header
      awk -F"$US" -v g="$g" '$1 == g {print $2}' "$tmp" | sort -u | while read -r sg; do
        [[ -z "$sg" ]] && continue
        printf '### %s\n' "$sg"
        awk -F"$US" -v g="$g" -v sg="$sg" '$1 == g && $2 == sg' "$tmp" | sort -t "$US" -k3,3 | while IFS="$US" read -r _group _subgroup rel title desc motion segment last_reviewed; do
          _r_render_entry "$rel" "$title" "$desc" "$motion" "$segment" "$last_reviewed"
        done
        printf '\n'
      done
    fi
  done

  local total_all=$((total_shared + total_functions + total_sources + total_meta))
  printf '%s\n' '---'
  printf '*Catalog entries: %d pages | %d shared | %d functions | %d sources | %d meta*\n' \
    "$total_all" "$total_shared" "$total_functions" "$total_sources" "$total_meta"

  rm -f "$tmp"
}

ci_cmd_reindex() {
  local check=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --check) check=1; shift ;;
      -h|--help)
        cat <<'EOF'
ci reindex [--check]

Regenerates index.md from page frontmatter.

  (no flag)  write index.md with the regenerated catalog
  --check    compare committed index.md to fresh generation;
             exit 2 (stale) or 0 (current)
EOF
        return 0 ;;
      -*) ci_err "reindex: unknown flag: $1"; return 3 ;;
      *) ci_err "reindex: unknown arg: $1"; return 3 ;;
    esac
  done

  local root target
  root=$(ci_repo_root)
  target="${root}/index.md"

  local generated
  generated=$(_r_generate)

  if [[ "$check" -eq 1 ]]; then
    local committed
    committed=$(cat "$target" 2>/dev/null || true)
    # Mask the dynamic header lines (timestamp, commit SHA) so --check
    # compares only the structural content. The bootstrap commit writes
    # a committed file whose timestamp will immediately be older than
    # any fresh regeneration; we compare the rest.
    local strip_header='1,/^## /{/^> Last regenerated:/d;}'
    local gen_norm comm_norm
    gen_norm=$(printf '%s\n' "$generated" | sed "${strip_header}")
    comm_norm=$(printf '%s\n' "$committed" | sed "${strip_header}")
    if [[ "$gen_norm" != "$comm_norm" ]]; then
      echo "reindex: index.md is stale relative to current frontmatter" >&2
      diff <(printf '%s\n' "$comm_norm") <(printf '%s\n' "$gen_norm") | head -n 40 >&2
      return 2
    fi
    echo "reindex: index.md is current (structural match; timestamp header ignored)"
    return 0
  fi

  printf '%s\n' "$generated" > "$target"
  echo "reindex: wrote ${target}"
}
